apiVersion: v1
kind: Service
metadata:
  annotations:
#    external-dns.alpha.kubernetes.io/hostname: t1.k.temsa.click
#    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  name: t1-mealstagram-service
  labels:
    app.kubernetes.io/name: t1-mealstagram-app
spec:
  selector:
    app.kubernetes.io/name: t1-mealstagram-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090    
