apiVersion: v1
kind: Service
metadata:
  name: argocd-service2
spec:
  selector:
    app.kubernetes.io/name: argocd-web
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31001
    port: 80
    targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:724772050614:certificate/7499b74b-9816-4cf5-8917-d55b3f7e2564"
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/load-balancer-name: myeks-ingress-alb
    alb.ingress.kubernetes.io/group.name: study
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - host: tt.k.temsa.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-service2