apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
      - name: app-with-actions
        image: hgreen726/app-with-actions:55ed58dd334d06b13dbd777b2a8403be4c9ea966
