apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
      - name: app-with-actions
        image: 724772050614.dkr.ecr.ap-northeast-2.amazonaws.com/app-with-actions:251cea2c1b90df76d3546c60f0a5d8adc6f4460f
