apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tt.k.temsa.click
  name: argocd-service
spec:
  selector:
    app.kubernetes.io/name: argocd-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    nodePort: 31001
    port: 80
    targetPort: 8080
